### ISSUE TITLE
纯http客户端请求如何构建

### ISSUE THREAD

**Issue by crawlersick** [lycclsltt/sunyata#1]
如题，即我不安装这个包，我客户端请求要使用http工具做rpc调用，如何使用如curl这样的工具发送一个http rpc调用请求呢？

**Comment by lycclsltt** [comment]
请求时候会把参数（可能是基本类型int, string，也可能是Python中的一个对象Class）序列化为二进制传输的，因此目前不能直接用curl

**Comment by lycclsltt** [comment]
curl的前提一定是参数全部为基础类型int string等，不能出现对象。

**Comment by crawlersick** [comment]
嗯嗯理解，就是它post的数据是python的序列化数据，纯用curl工具没办法复现这个数据。
不过是不是可以考虑把这个功能加入呢？比如可以服务端接受json化文本化的python对象？

**Comment by lycclsltt** [comment]
嗯嗯，考虑加入

**Comment by lycclsltt** [comment]
> 嗯嗯理解，就是它post的数据是python的序列化数据，纯用curl工具没办法复现这个数据。
> 不过是不是可以考虑把这个功能加入呢？比如可以服务端接受json化文本化的python对象？

嗯嗯，考虑加入
